# Generated by Django 5.0.4 on 2024-04-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
