# Generated by Django 5.0.4 on 2024-04-14 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_info_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='reaccelai_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
