# Generated by Django 5.0.4 on 2024-04-15 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_info_reaccelai_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='signup_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
