# Generated by Django 5.0.4 on 2024-04-17 12:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_info_signup_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='signup_timestamp',
        ),
        migrations.AddField(
            model_name='user_info',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='reaccelai_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
