# Generated by Django 5.0.4 on 2024-04-29 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_login_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_history',
            old_name='email',
            new_name='user_info',
        ),
    ]
