# Generated by Django 5.0.3 on 2024-06-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='learning_rate',
            field=models.FloatField(),
        ),
    ]
