# Generated by Django 5.0.3 on 2024-06-12 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_uploadedfile_learning_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_at',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=100)),
                ('reaccel_id', models.CharField(max_length=100)),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='reaccel_id',
            field=models.CharField(max_length=100),
        ),
    ]
