# Generated by Django 5.0.3 on 2024-06-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_login_at_alter_uploadedfile_reaccel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='model_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
