# Generated by Django 5.0.3 on 2024-06-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_iam_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='iam_users',
            new_name='my_iam_users',
        ),
    ]
