# Generated by Django 5.0.3 on 2024-06-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_iam_users_my_iam_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_iam_users',
            new_name='admin_iam_users',
        ),
    ]
