# Generated by Django 5.0.3 on 2024-06-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_my_iam_users_admin_iam_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_iam_users',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
