# Generated by Django 5.0.3 on 2024-06-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_admin_iam_users_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_iam_users',
            name='acceleration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_iam_users',
            name='dashboard',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_iam_users',
            name='model_creation',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_iam_users',
            name='performance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_iam_users',
            name='test_model',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_iam_users',
            name='track_yourself',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
