# Generated by Django 5.0.3 on 2024-06-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_admin_iam_users_acceleration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='allpermissions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
