# Generated by Django 5.0.3 on 2024-06-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_user_info_allpermissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_iam_users',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin_iam_users',
            name='iam_user_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
