# Generated by Django 5.0.3 on 2024-06-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_admin_iam_users_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_iam_users',
            name='others',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
